### ISSUE TITLE
Structure development of cosmos-js lib

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/js-cosmos#2]
A lot of questions:
1. Product owner needed
2. When and how original code will become a part of this repo?
3. Planning of initial release
4. Responsible for documentation
5. Preparation for open sourcing

**Comment by mastercyb** [comment]
I would love to discuss architecture considerations right here in the issue. Not in private chats. I know @npopeka has very interesting architecture picture and @litvintech has analysis of what is currently wrong. Cmon guys.. Its very important for us to move on this issue

**Comment by cyborgshead** [comment]
I'm going to lead this project as I described before.
Now js-cosmos have from the ground up the code base and also we are using js-amino actively
The initial release which we planned with multichain support is coming and have a basic documentation
We ready to start community onboarding right now, but need the critical feature for bigger adoption - ledger support which will come in a couple of weeks with next release
