### ISSUE TITLE
Prepare 1.0.0 release of js-cosmos

### ISSUE THREAD

**Issue by cyborgshead** [cybercongress/js-cosmos#4]
- [x] Add CI
- [x] Add tests
- [x] Create issue templates (Bug report, Feature request, Add Issue to Gitcoin)
- [x] Create PR template
- [x] Describe features (AS-IS) in README
- [x] Describe known bugs (TO-FI ) in README
- [x] Describe planned features (TO-DO) in README
- [x] Add logo to README
- [x] Add badges to README (test's coverage, npm, issues, gitcoin, license, PR)
- [x] Describe Pull Requesing flow in README (Add at CONTRIBUTING.md)
- [x] Add list of maintainers and contributors to README
- [x] Add Gitcoin program description to README
- [x] Great auto changelog
- [x] Add contributing.md
- [x] Add code of conduct
- [x] Add docs folder
- [x] Add auto docs collector

**Comment by MicrowaveDev** [comment]
@litvintech You can find features describing in there: https://github.com/cybercongress/js-cosmos/pull/3
Also need some CI for running tests in PR.

**Comment by SaveTheAles** [comment]
Almost done

we need to: 
- [ ] create logo
- [ ] define overview section
- [ ]  define TODO section
- [ ] define TOFI section 

@Jonybang @litvintech need your help
